# docker-compose.yml for initializing Solr.
version: '3'

services:
  remove:
    command: >
      sh -c '
        rm -rf /code/remove
        exit 0
      '
    image: ubuntu:22.04
    networks:
      - app_net
    # SolrとZooKeeperを初期化するために、永続化している
    # /java/solr-data
    # /java/zoo-keeper/zooX/data
    # /java/zoo-keeper/zooX/datalog
    # を空にする必要があった。
    volumes:
      - ./java/solr-data/data:/code/remove/solr/data
      - ./java/zoo-keeper/zoo1/data:/code/remove/zoo1/data
      - ./java/zoo-keeper/zoo1/datalog:/code/remove/zoo1/datalog
      - ./java/zoo-keeper/zoo2/data:/code/remove/zoo2/data
      - ./java/zoo-keeper/zoo2/datalog:/code/remove/zoo2/datalog
      - ./java/zoo-keeper/zoo3/data:/code/remove/zoo3/data
      - ./java/zoo-keeper/zoo3/datalog:/code/remove/zoo3/datalog

  python:
    command: >
      sh -c '
        ./entrypoint.sh
        ./solr.sh
        /bin/sh
      '
    tty: true
    volumes:
      - ./python/web_crawler:/code/web_crawler
      - ./solr.sh:/code/solr.sh

  # Solrのファイルを削除したいので、Solrよりも先にremoveを起動したい。
  # SolrはZooKeeperの後で立ち上がるので、ZooKeeperをremoveの後で立ち上げる。
  # Solrのdepends_onを上書きするのはややこしくなりそうなので避けた。
  zoo1:
    depends_on:
      remove:
        condition: service_completed_successfully
  
  zoo2:
    depends_on:
      remove:
        condition: service_completed_successfully
  
  zoo3:
    depends_on:
      remove:
        condition: service_completed_successfully
