version: '3'

services:
  nginx: 
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    ports:
      # ホスト側:コンテナ側
      - 80:80
      - 8000:8000
    volumes:
      - ./webserver/conf.d:/etc/nginx/conf.d
      - ./webserver/logs:/var/log/nginx
      - ./uwsgi/uwsgi_params:/etc/nginx/uwsgi_params
      - ./socket:/run  # unix domain socket でpythonコンテナと通信するために必要
      - ./twels/static:/twels/static
    depends_on:
      - python
    restart: always

  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    command: >
      sh -c '
        ./entrypoint.sh
        uwsgi /code/uwsgi/uwsgi.ini
      '
    volumes: 
      - ./twels:/code/twels
      - ./wiki_crawler:/code/wiki_crawler
      - ./uwsgi:/code/uwsgi
      - ./.env:/code/.env  # for django-environ
      - ./socket:/run  # unix domain socket でNginxコンテナと通信するために必要
    environment:
      - PYTHONPATH=/code
    networks:
      - app_net
    restart: always

  db:
    container_name: $DB_CONTAINER_NAME
    image: mysql:$MYSQL_VERSION
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MY_ROOT_PASSWORD
      MYSQL_DATABASE: $MY_DB_NAME  # イメージの起動時に作成するデータベースの名前
      MYSQL_USER: hisashi
      MYSQL_PASSWORD: $MY_HISASHI_PASSWORD
    volumes:
      - ./db/mysql:/var/lib/mysql  # 永続化
      - ./db/conf:/etc/mysql/conf.d  # custom configのマウント
      - ./db/logs:/var/log/mysql
      - ./initdb:/docker-entrypoint-initdb.d  # ここにマウントしたディレクトリにあるファイルは，mysqlディレクトリが空の場合，起動時に実行される
    networks:
      - app_net
    restart: always

networks:
  app_net:
    driver: bridge