version: '3'

services:
  python:
    volumes: 
      - ./front:/code/front  # TODO: frontをvolumeする必要があるか確認．
      - ./wiki_crawler:/code/wiki_crawler
    tty: true

  db:
    volumes:
      # ここだけdocker-compose.ymlを上書きする．
      # mysqlディレクトリが空の場合，テーブルを作成して，データは空のままにしていたい．
      - ./sqls/initdb:/docker-entrypoint-initdb.d