# this file contains our base configuration.
version: '3'

services:
  python:
    container_name: $PYTHON_CONTAINER_NAME
    build:
      context: .
      dockerfile: ./python/Dockerfile
    command: >
      sh -c '
        ./entrypoint.sh
        uwsgi /code/uwsgi/uwsgi.ini
      '
    volumes:
      - ./.env:/code/.env  # for django-environ
      - ./twels:/code/twels  # own packages
    environment:
      - PYTHONPATH=/code
    networks:
      - app_net

  db:
    container_name: $DB_CONTAINER_NAME
    image: mysql:$MYSQL_VERSION
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MY_ROOT_PASSWORD
      MYSQL_DATABASE: $MY_DB_NAME  # イメージの起動時に作成するデータベースの名前
      MYSQL_USER: hisashi
      MYSQL_PASSWORD: $MY_HISASHI_PASSWORD
    volumes:
      - ./db/mysql:/var/lib/mysql  # 永続化
      - ./db/conf:/etc/mysql/conf.d  # custom configのマウント
      - ./db/logs:/var/log/mysql
      - ./initdb:/docker-entrypoint-initdb.d  # ここにマウントしたディレクトリにあるファイルは，mysqlディレクトリが空の場合，起動時に実行される
    networks:
      - app_net

networks:
  app_net:
    driver: bridge