# docker-compose.yml for initializing Solr.
version: '3'

services:
  remove:
    command: rm -rf /code/remove
    image: ubuntu:22.04
    networks:
      - app_net
    # Solrを初期化するために、永続化している
    # /java/solr-data
    # を空にする必要があった。
    volumes:
      - ./java/solr-data/data:/code/remove/solr/data

  python:
    # remove old data.
    # Solrコンテナが起動するのを待つためにsleepを入れている。
    # docker-compose.ymlのdepends_onのservice_healthyを活用しても良いと思う。
    command: >
      sh -c '
        sleep 10
        ./entrypoint.sh
        ./solr.sh
        /bin/sh
      '
    tty: true
    volumes:
      - ./python/web_crawler:/code/web_crawler
      - ./solr.sh:/code/solr.sh

  # Solrのファイルを削除したいので、Solrよりも先にremoveを起動したい。
  # SolrはZooKeeperの後で立ち上がるので、ZooKeeperをremoveの後で立ち上げる。
  # Solrのdepends_onを上書きするのはややこしくなりそうなので避けた。
  zoo1:
    depends_on:
      - remove
  
  zoo2:
    depends_on:
      - remove
  
  zoo3:
    depends_on:
      - remove
