# Generated by Django 4.2 on 2023-06-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unselect this instead of deleting accounts."is_active" indicates whether this Emailuser is currently logged in.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='"is_active" indicates whether this user is active.Unselect this instead of deleting accounts.True if the user has completed registration, False if the user is in a temporary registration state.', verbose_name='active'),
        ),
    ]
