# Generated by Django 4.1.3 on 2022-12-31 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailloginrequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 31, 11, 19, 34, 502993), null=True, verbose_name='first request date'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 31, 11, 19, 34, 500406), null=True, verbose_name='first request date'),
        ),
        migrations.AlterField(
            model_name='usercreaterequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 31, 11, 19, 34, 501127), null=True, verbose_name='first request date'),
        ),
    ]
