# Generated by Django 4.1.3 on 2023-01-15 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_emailloginrequest_first_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailloginrequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 0, 20, 34, 775888), null=True, verbose_name='first request date'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 0, 20, 34, 771216), null=True, verbose_name='first request date'),
        ),
        migrations.AlterField(
            model_name='usercreaterequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 0, 20, 34, 773785), null=True, verbose_name='first request date'),
        ),
    ]
