# Generated by Django 4.1.3 on 2023-01-15 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_emailloginrequest_first_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailloginrequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 0, 23, 9, 207658), null=True, verbose_name='first request date'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 0, 23, 9, 204954), null=True, verbose_name='first request date'),
        ),
        migrations.AlterField(
            model_name='usercreaterequest',
            name='first_request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 15, 0, 23, 9, 206010), null=True, verbose_name='first request date'),
        ),
    ]
