name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master and develop branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: foo  # incorrect value

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # This action check-out my repository under $GITHUB_WORKSPACE, 
      # so my workflow can access it.
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2  # setup-python version is 2
        with: 
          python-version: '3.10.0'
          
      - name: Update pip
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r python/requirements.txt
      
      - name: check Django DEBUG = False
        run: pytest tests/test_settings.py
